apiVersion: v1
kind: Service
metadata:
  labels:
    app: udaconnect-location-producer
  name: udaconnect-location-producer
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30005
  selector:
    app: udaconnect-location-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udaconnect-location-producer
  name: udaconnect-location-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udaconnect-location-producer
  template:
    metadata:
      labels:
        app: udaconnect-location-producer
    spec:
      containers:
      - image: hongviet119/udaconnect-location-producer:latest
        name: udaconnect-location-producer
        imagePullPolicy: Always
        env:
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: udaconnect-kafka-env
              key: KAFKA_TOPIC
        - name: KAFKA_HOST
          valueFrom:
            configMapKeyRef:
              name: udaconnect-kafka-env
              key: KAFKA_HOST
      restartPolicy: Always
